language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1

branches:
  only:
    - master

services:
  - docker

before_script:
  - dotnet restore ScupTel/ScupTel.sln 
  - docker run -d -p 1433:1433 -e SA_PASSWORD=scupTel.8520 -e ACCEPT_EULA=Y --name mssql microsoft/mssql-server-linux
  - docker inspect mssql

script:
  - dotnet test ScupTel/ScupTel.Tests.UnitTests/ScupTel.Tests.UnitTests.csproj
  - dotnet test ScupTel/ScupTel.Tests.IntegrationTests/ScupTel.Tests.IntegrationTests.csproj